use googleapis_tonic_google_bigtable_v2::google::bigtable::v2::{
    r#type, r#type::Kind as TypeKind, Type, Value,
};

/// Represents a type-safe GoogleSQL data type schema for Cloud Bigtable parameters.
#[derive(Clone, Debug, PartialEq)]
pub enum SqlType {
    String,
    Int64,
    Bool,
    Bytes,
    Float32,
    Float64,
    Timestamp,
    Date,
    Array(Box<SqlType>),
    Struct(Vec<(String, SqlType)>),
    Map {
        key_type: Box<SqlType>,
        value_type: Box<SqlType>,
    },
}

impl SqlType {
    /// Serializes this type-safe SQL type into the autogenerated Tonic Protobuf `Type` message payload.
    pub fn to_pb(&self) -> Type {
        let kind = match self {
            SqlType::String => Some(TypeKind::StringType(r#type::String::default())),
            SqlType::Int64 => Some(TypeKind::Int64Type(r#type::Int64::default())),
            SqlType::Bool => Some(TypeKind::BoolType(r#type::Bool::default())),
            SqlType::Bytes => Some(TypeKind::BytesType(r#type::Bytes::default())),
            SqlType::Float32 => Some(TypeKind::Float32Type(r#type::Float32::default())),
            SqlType::Float64 => Some(TypeKind::Float64Type(r#type::Float64::default())),
            SqlType::Timestamp => Some(TypeKind::TimestampType(r#type::Timestamp::default())),
            SqlType::Date => Some(TypeKind::DateType(r#type::Date::default())),
            SqlType::Array(element_type) => Some(TypeKind::ArrayType(Box::new(r#type::Array {
                element_type: Some(Box::new(element_type.to_pb())),
            }))),
            SqlType::Struct(fields) => {
                use googleapis_tonic_google_bigtable_v2::google::bigtable::v2::r#type::r#struct::Field;
                let pb_fields = fields
                    .iter()
                    .map(|(name, st)| Field {
                        field_name: name.clone(),
                        r#type: Some(st.to_pb()),
                    })
                    .collect();
                Some(TypeKind::StructType(r#type::Struct {
                    fields: pb_fields,
                    encoding: None,
                }))
            }
            SqlType::Map {
                key_type,
                value_type,
            } => Some(TypeKind::MapType(Box::new(r#type::Map {
                key_type: Some(Box::new(key_type.to_pb())),
                value_type: Some(Box::new(value_type.to_pb())),
            }))),
        };
        Type { kind }
    }

    /// Parses a Tonic protobuf `Type` back into the type-safe `SqlType` representation.
    pub fn from_pb(pb: &Type) -> Option<Self> {
        let kind = pb.kind.as_ref()?;
        match kind {
            TypeKind::StringType(_) => Some(SqlType::String),
            TypeKind::Int64Type(_) => Some(SqlType::Int64),
            TypeKind::BoolType(_) => Some(SqlType::Bool),
            TypeKind::BytesType(_) => Some(SqlType::Bytes),
            TypeKind::Float32Type(_) => Some(SqlType::Float32),
            TypeKind::Float64Type(_) => Some(SqlType::Float64),
            TypeKind::TimestampType(_) => Some(SqlType::Timestamp),
            TypeKind::DateType(_) => Some(SqlType::Date),
            TypeKind::ArrayType(arr) => {
                let element = arr.element_type.as_ref()?;
                let parsed_element = SqlType::from_pb(element)?;
                Some(SqlType::Array(Box::new(parsed_element)))
            }
            TypeKind::StructType(st) => {
                let mut fields = Vec::new();
                for field in &st.fields {
                    let field_type = field.r#type.as_ref()?;
                    let parsed_field = SqlType::from_pb(field_type)?;
                    fields.push((field.field_name.clone(), parsed_field));
                }
                Some(SqlType::Struct(fields))
            }
            TypeKind::MapType(m) => {
                let k_type = m.key_type.as_ref()?;
                let v_type = m.value_type.as_ref()?;
                let parsed_k = SqlType::from_pb(k_type)?;
                let parsed_v = SqlType::from_pb(v_type)?;
                Some(SqlType::Map {
                    key_type: Box::new(parsed_k),
                    value_type: Box::new(parsed_v),
                })
            }
            _ => None,
        }
    }
}

/// Extension trait designed to attach ergonomic schema mapping decorators
/// directly onto the autogenerated gRPC `Value` message.
pub trait ValueExt {
    /// Binds an explicit `SqlType` schema descriptor directly onto the parameter value payload.
    /// This completely bypasses the dynamic type inference pipeline.
    fn with_type(self, sql_type: SqlType) -> Self;
}

impl ValueExt for Value {
    fn with_type(mut self, sql_type: SqlType) -> Self {
        self.r#type = Some(sql_type.to_pb());
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Helper: round-trip a SqlType through to_pb → from_pb and assert equality.
    fn roundtrip(sql_type: SqlType) {
        let pb = sql_type.clone().to_pb();
        let recovered = SqlType::from_pb(&pb)
            .unwrap_or_else(|| panic!("from_pb returned None for {:?}", sql_type));
        assert_eq!(
            recovered, sql_type,
            "roundtrip mismatch for {:?}",
            sql_type
        );
    }

    #[test]
    fn to_pb_from_pb_roundtrip_scalar_types() {
        roundtrip(SqlType::String);
        roundtrip(SqlType::Int64);
        roundtrip(SqlType::Bool);
        roundtrip(SqlType::Bytes);
        roundtrip(SqlType::Float32);
        roundtrip(SqlType::Float64);
        roundtrip(SqlType::Timestamp);
        roundtrip(SqlType::Date);
    }

    #[test]
    fn to_pb_from_pb_roundtrip_array() {
        roundtrip(SqlType::Array(Box::new(SqlType::String)));
        roundtrip(SqlType::Array(Box::new(SqlType::Int64)));
        // Nested arrays
        roundtrip(SqlType::Array(Box::new(SqlType::Array(Box::new(
            SqlType::Bool,
        )))));
    }

    #[test]
    fn to_pb_from_pb_roundtrip_struct() {
        roundtrip(SqlType::Struct(vec![
            ("name".to_string(), SqlType::String),
            ("age".to_string(), SqlType::Int64),
            ("active".to_string(), SqlType::Bool),
        ]));
        // Empty struct
        roundtrip(SqlType::Struct(vec![]));
    }

    #[test]
    fn to_pb_from_pb_roundtrip_map() {
        roundtrip(SqlType::Map {
            key_type: Box::new(SqlType::String),
            value_type: Box::new(SqlType::Int64),
        });
        roundtrip(SqlType::Map {
            key_type: Box::new(SqlType::Bytes),
            value_type: Box::new(SqlType::Bool),
        });
    }

    #[test]
    fn to_pb_from_pb_roundtrip_nested_complex_types() {
        // Array of structs
        roundtrip(SqlType::Array(Box::new(SqlType::Struct(vec![
            ("id".to_string(), SqlType::Int64),
            ("label".to_string(), SqlType::String),
        ]))));
        // Map with array values
        roundtrip(SqlType::Map {
            key_type: Box::new(SqlType::String),
            value_type: Box::new(SqlType::Array(Box::new(SqlType::Float64))),
        });
    }

    #[test]
    fn from_pb_returns_none_for_empty_kind() {
        let pb = Type { kind: None };
        assert!(
            SqlType::from_pb(&pb).is_none(),
            "from_pb should return None when kind is absent"
        );
    }

    #[test]
    fn with_type_attaches_type_descriptor_to_value() {
        let value = Value {
            kind: Some(googleapis_tonic_google_bigtable_v2::google::bigtable::v2::value::Kind::FloatValue(3.14)),
            ..Default::default()
        };
        assert!(value.r#type.is_none());

        let value_with_type = value.with_type(SqlType::Float64);
        let attached = value_with_type.r#type.unwrap();
        assert!(
            matches!(
                attached.kind,
                Some(googleapis_tonic_google_bigtable_v2::google::bigtable::v2::r#type::Kind::Float64Type(_))
            ),
            "with_type should attach the Float64 type descriptor"
        );
    }
}
