use googleapis_tonic_google_bigtable_v2::google::bigtable::v2::{
    r#type, r#type::Kind as TypeKind, Type, Value,
};

/// Represents a type-safe GoogleSQL data type schema for Cloud Bigtable parameters.
#[derive(Clone, Debug, PartialEq)]
pub enum SqlType {
    String,
    Int64,
    Bool,
    Bytes,
    Float32,
    Float64,
    Timestamp,
    Date,
    Array(Box<SqlType>),
    Struct(Vec<(String, SqlType)>),
    Map {
        key_type: Box<SqlType>,
        value_type: Box<SqlType>,
    },
}

impl SqlType {
    /// Serializes this type-safe SQL type into the autogenerated Tonic Protobuf `Type` message payload.
    pub fn to_pb(&self) -> Type {
        let kind = match self {
            SqlType::String => Some(TypeKind::StringType(r#type::String::default())),
            SqlType::Int64 => Some(TypeKind::Int64Type(r#type::Int64::default())),
            SqlType::Bool => Some(TypeKind::BoolType(r#type::Bool::default())),
            SqlType::Bytes => Some(TypeKind::BytesType(r#type::Bytes::default())),
            SqlType::Float32 => Some(TypeKind::Float32Type(r#type::Float32::default())),
            SqlType::Float64 => Some(TypeKind::Float64Type(r#type::Float64::default())),
            SqlType::Timestamp => Some(TypeKind::TimestampType(r#type::Timestamp::default())),
            SqlType::Date => Some(TypeKind::DateType(r#type::Date::default())),
            SqlType::Array(element_type) => Some(TypeKind::ArrayType(Box::new(r#type::Array {
                element_type: Some(Box::new(element_type.to_pb())),
            }))),
            SqlType::Struct(fields) => {
                use googleapis_tonic_google_bigtable_v2::google::bigtable::v2::r#type::r#struct::Field;
                let pb_fields = fields
                    .iter()
                    .map(|(name, st)| Field {
                        field_name: name.clone(),
                        r#type: Some(st.to_pb()),
                    })
                    .collect();
                Some(TypeKind::StructType(r#type::Struct {
                    fields: pb_fields,
                    encoding: None,
                }))
            }
            SqlType::Map {
                key_type,
                value_type,
            } => Some(TypeKind::MapType(Box::new(r#type::Map {
                key_type: Some(Box::new(key_type.to_pb())),
                value_type: Some(Box::new(value_type.to_pb())),
            }))),
        };
        Type { kind }
    }
}

/// Extension trait designed to attach ergonomic schema mapping decorators
/// directly onto the autogenerated gRPC `Value` message.
pub trait ValueExt {
    /// Binds an explicit `SqlType` schema descriptor directly onto the parameter value payload.
    /// This completely bypasses the dynamic type inference pipeline.
    fn with_type(self, sql_type: SqlType) -> Self;
}

impl ValueExt for Value {
    fn with_type(mut self, sql_type: SqlType) -> Self {
        self.r#type = Some(sql_type.to_pb());
        self
    }
}
